Agent:
  model_id: "deepseek-chat"
  host_locally: False  
  base_url: "https://api.deepseek.com"
  api_key: "sk-686ff11433504a54bac51df6a77c6123"
  menu_return_length: 500
  response_return_length: 500
  debug: True

Data: 
  data_root_dir: "data/files/"
  data_node_save_dir: "data/data_nodes/"

Scraper: 
  model_id: "deepseek-chat"
  base_url: "https://api.deepseek.com"
  api_key: "sk-686ff11433504a54bac51df6a77c6123"


  


