Agent:
  model_id:  # your model id here
  host_locally: False  
  base_url:  # your host here
  api_key:   # your pai here
  menu_return_length: 500
  response_return_length: 500
  debug: True

Data: 
  data_root_dir: "data/files/"
  data_node_save_dir: "data/data_nodes/"

Scraper: 
  model_id:  # set a model id for scraper, can be the same to the Agent
  base_url:  # set scraper host id here
  api_key:  #


  


