name: retaillm
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - python=3.11.10
  - pip=24.2
  - setuptools
  - wheel
  - pip:
      - aiohttp==3.11.8
      - certifi==2024.8.30
      - click==8.1.7
      - fsspec==2024.10.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - langchain==0.3.9
      - langchain-core==0.3.21
      - matplotlib==3.9.2
      - networkx==3.4.2
      - numpy==1.26.4
      - openai==1.54.5
      - pandas==2.2.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - torch==2.5.1
      - tqdm==4.67.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - websocket-client==1.8.0
      - yarl==1.18.0

