Agent:
  model_id: "Qwen2.5-72B-Instruct"
  host_locally: False  
  base_url: "http://36.134.165.224:6006/v1/"
  api_key: "xxx"
  menu_return_length: 500
  response_return_length: 500
  debug: True

Data: 
  data_root_dir: "data/files/"
  data_node_save_dir: "data/data_nodes/"


  


